const ProjectStructureGuidePage = () => (
  <div className="p-8 max-w-3xl">
    <h1 className="text-3xl font-semibold text-neutral-300 mb-4">Project Structure Guide</h1>
    <p className="text-neutral-400 mb-4">Understand the folder and file structure generated by BuiltStack.</p>
    <ul className="list-disc list-inside text-neutral-400 mb-4 space-y-2">
      <li><b>apps/</b>: Contains your main applications (web, docs, etc.).</li>
      <li><b>packages/</b>: Shared code, UI components, configs, and utilities.</li>
      <li><b>public/</b>: Static assets like images and logos.</li>
      <li><b>app/</b>: Next.js app directory (routes, pages, components).</li>
      <li><b>bin/</b>: CLI entry points and scripts.</li>
    </ul>
    <p className="text-neutral-400">Each folder is modular and can be extended as your project grows.</p>
  </div>
);

export default ProjectStructureGuidePage;
